[package]
name = "rest_api"
version = "0.1.0"
edition = "2021"

[dependencies]
memory-stats = "1.1.0"
serde = "1.0.201"
serde_derive = "1.0.201"
tokio = { version = "1.37.0", features = ["full"] }
warp = "0.3.7"
